- name: Check for apt lock holder
  shell: |
    fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/lib/apt/lists/lock || true
  register: lock_holder
  changed_when: false

- name: Kill apt lock holder if exists
  shell: |
    fuser -k /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/lib/apt/lists/lock || true
  when: lock_holder.stdout != ""
  changed_when: false

- name: Remove stale apt lock files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/apt/lists/lock
    - /var/lib/dpkg/lock-frontend
    - /var/lib/dpkg/lock
